import glob
import time

print( "// Generated by Philip's python on " + time.strftime("%c"))
print('''digraph TT_447{
ranksep=2;
{node [style=filled, fillcolor="gray"]; Legend_Missions;''')

for fileName in glob.iglob("M_*.ev3p"):
     node = fileName[:-5]
     print('{0};'.format(node))
print('}')

for fileName in glob.iglob("*.ev3p"):
   node = fileName[:-5]
   f = open(fileName)
   list = []
   for line in f:
       if line.find('.ev3p') != -1:
          begin = line.find('Target') + 8
          end = line.find('\\.ev3p')
          myBlock = line[begin:end]
          if myBlock not in list:
              list.append(myBlock)  
   if not list:
       print( '"{0}"'.format(node))
   else:
       for item in list:
           print( '"{0}"->"{1}"'.format(node,item))
   f.close()
print('''
subgraph legend {
	rank = sink;
            Legend_Missions [label="Missions"];
            Legend_MyBlocks [label="MyBlocks"];
    }
}''')

   
   
   
   
