import glob
import time

print( "// Generated by Philip's python on " + time.strftime("%c"))
print('''digraph TT_447{
ranksep=2;
ratio=compress; size="7.5,10"
node [fontname="Arial", fontsize=30];
{node [style=filled, fillcolor="gray"];''')

for fileName in glob.iglob("M_*.ev3p"):
     node = fileName[:-5]
     print('{0};'.format(node))
print('}')

for fileName in glob.iglob("*.ev3p"):
   node = fileName[:-5]
#Python 2
   f = open(fileName)
#Python 3
#   f = open(fileName, encoding='utf-8')
####
   
   list = []
   for line in f:
       if line.find('.ev3p') != -1:
          begin = line.find('Target') + 8
          end = line.find('\\.ev3p')
          myBlock = line[begin:end]
          if myBlock not in list:
              list.append(myBlock)  
   if not list:
       print( '"{0}"'.format(node))
   else:
       for item in list:
           string = '"{0}"->"{1}"'.format(node,item);
           if node[:2] == "M_":
              print(string + '[color=blue]')
           else:
              print(string)
   f.close()
print('}')

   
   
   
   
